version: '3'
services:
  db:
    image: 'mongo'
    container_name: 'db'
    ports:
      - '27017-27019:27017-27019'

  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: 'app'
    ports:
      - '8080:8080'
    environment:
      - spring.data.mongodb.host=db
      - tst.locj.doodle.mongdb.cluster.host=db
